# Generated by Django 5.2.8 on 2026-09-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('editor', 'Editor'), ('moderator', 'Moderator'), ('author', 'Author'), ('contributor', 'Contributor'), ('member', 'Member'), ('user', 'User')], default='author', help_text='Determines what this account may do. See Role for the ladder.', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='suspended_until',
            field=models.DateTimeField(blank=True, help_text='Leave empty for an indefinite suspension.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='suspension_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
