# Generated by Django 5.2.8 on 2026-09-02 06:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_archived_at_post_canonical_url_post_deleted_at_and_more'),
        ('user', '0004_backfill_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicFollow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='post.category')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='post.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_follows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='user_topicf_user_id_fc4c23_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('category__isnull', False)), fields=('user', 'category'), name='unique_category_follow'), models.UniqueConstraint(condition=models.Q(('tag__isnull', False)), fields=('user', 'tag'), name='unique_tag_follow'), models.CheckConstraint(condition=models.Q(models.Q(('category__isnull', False), ('tag__isnull', True)), models.Q(('category__isnull', True), ('tag__isnull', False)), _connector='OR'), name='topic_follow_exactly_one_target')],
            },
        ),
    ]
