# Generated by Django 5.2.8 on 2026-09-02 03:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_bookmark_editorimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
