# Generated by Django 5.2.8 on 2026-09-02 06:09

import blog_server.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_preview_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='canonical_url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='post',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='seo_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='seo_title',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', 'Everyone'), ('members', 'Members only'), ('private', 'Only me')], default='public', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('scheduled', 'Scheduled'), ('published', 'Published')], default='draft', max_length=12),
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('cover', models.ImageField(blank=True, upload_to='series/', validators=[blog_server.validators.validate_image_upload])),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'series',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeriesPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_entries', to='post.post')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='post.series')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='SeriesProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_progress', to='post.post')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='post.series')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='PostRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('excerpt', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_revisions', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='post.post')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['post', '-created_at'], name='post_postre_post_id_aac176_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReadingHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('is_finished', models.BooleanField(default=False)),
                ('last_read_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_history', to='post.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_read_at'],
                'indexes': [models.Index(fields=['user', '-last_read_at'], name='post_readin_user_id_0fcb82_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'post'), name='unique_reading_history')],
            },
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['author', '-created_at'], name='post_series_author__3bdac4_idx'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['slug'], name='post_series_slug_654727_idx'),
        ),
        migrations.AddIndex(
            model_name='seriespost',
            index=models.Index(fields=['series', 'position'], name='post_series_series__c0e0ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='seriespost',
            constraint=models.UniqueConstraint(fields=('series', 'post'), name='unique_series_post'),
        ),
        migrations.AddConstraint(
            model_name='seriespost',
            constraint=models.UniqueConstraint(fields=('series', 'position'), name='unique_series_position'),
        ),
        migrations.AddIndex(
            model_name='seriesprogress',
            index=models.Index(fields=['user', 'series'], name='post_series_user_id_d009b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='seriesprogress',
            constraint=models.UniqueConstraint(fields=('user', 'series', 'post'), name='unique_series_progress'),
        ),
    ]
