# Generated by Django 5.2.8 on 2026-09-02 09:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_archived_at_post_canonical_url_post_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vector', models.JSONField(default=list)),
                ('model', models.CharField(max_length=100)),
                ('content_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='post.post')),
            ],
            options={
                'indexes': [models.Index(fields=['model'], name='post_postem_model_1efbae_idx')],
            },
        ),
    ]
