# Generated by Django 5.2.8 on 2026-09-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_post_review_note_post_reviewed_at_post_reviewed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='kind',
            field=models.CharField(choices=[('like', '👍 Like'), ('love', '❤️ Love'), ('insightful', '💡 Insightful'), ('funny', '😄 Funny')], default='like', max_length=12),
        ),
    ]
