# Generated by Django 5.2.8 on 2026-09-02 03:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comment', '0003_comment_is_hidden_commentreport'),
        ('post', '0004_post_preview_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verb', models.CharField(choices=[('like', 'liked your post'), ('comment', 'commented on your post'), ('reply', 'replied to your comment'), ('follow', 'started following you')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_sent', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='comment.comment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='post.post')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_fe3355_idx'), models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a95ed4_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('comment__isnull', True)), fields=('recipient', 'actor', 'verb', 'post'), name='unique_post_notification'), models.UniqueConstraint(condition=models.Q(('comment__isnull', False)), fields=('recipient', 'actor', 'verb', 'comment'), name='unique_comment_notification')],
            },
        ),
    ]
