# Generated by Django 5.2.8 on 2026-09-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notification_verb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('like', 'liked your post'), ('comment', 'commented on your post'), ('reply', 'replied to your comment'), ('follow', 'started following you'), ('submitted', 'submitted a post for review'), ('approved', 'published your post'), ('changes', 'asked for changes on your post'), ('mention', 'mentioned you in a comment')], max_length=20),
        ),
    ]
