import uuid

from django.conf import settings
from django.db import models


class NotificationQuerySet(models.QuerySet):
    def unread(self):
        return self.filter(is_read=False)

    def with_related(self):
        return self.select_related('actor', 'post', 'comment')


class Notification(models.Model):
    """
    Something that happened to the recipient's work.

    Notifications are generated by signals rather than by the views that cause
    them, so every path that creates a like, comment or follow — API, admin or
    management command — produces one without the caller remembering to.
    """

    class Verb(models.TextChoices):
        LIKE = 'like', 'liked your post'
        COMMENT = 'comment', 'commented on your post'
        REPLY = 'reply', 'replied to your comment'
        FOLLOW = 'follow', 'started following you'
        SUBMITTED = 'submitted', 'submitted a post for review'
        APPROVED = 'approved', 'published your post'
        CHANGES = 'changes', 'asked for changes on your post'
        MENTION = 'mention', 'mentioned you in a comment'

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    recipient = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='notifications',
    )
    # Null once the acting account is deleted; the notification itself survives.
    actor = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='notifications_sent',
    )
    verb = models.CharField(max_length=20, choices=Verb.choices)

    post = models.ForeignKey(
        'post.Post',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='notifications',
    )
    comment = models.ForeignKey(
        'comment.Comment',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='notifications',
    )

    is_read = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    objects = NotificationQuerySet.as_manager()

    class Meta:
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['recipient', 'is_read', '-created_at']),
            models.Index(fields=['recipient', '-created_at']),
        ]
        constraints = [
            # Unliking and liking again should not stack up duplicate rows.
            models.UniqueConstraint(
                fields=['recipient', 'actor', 'verb', 'post'],
                condition=models.Q(comment__isnull=True),
                name='unique_post_notification',
            ),
            models.UniqueConstraint(
                fields=['recipient', 'actor', 'verb', 'comment'],
                condition=models.Q(comment__isnull=False),
                name='unique_comment_notification',
            ),
        ]

    def __str__(self):
        return f'{self.actor} {self.get_verb_display()} -> {self.recipient}'

    @property
    def message(self):
        actor = self.actor.display_name if self.actor else 'Someone'
        return f'{actor} {self.get_verb_display()}'

    @property
    def target_url(self):
        """Where the frontend should go when the notification is clicked."""
        if self.post_id and self.post:
            return f'/post/{self.post.slug}'
        if self.actor:
            return f'/author/{self.actor.username}'
        return '/'
